### ISSUE TITLE
e2e test actually failing but still passing CI

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-sync#186]
**Describe the issue**
When we [run the](https://github.com/medic/cht-sync/blob/98771d2ea2c78ea27994d28d340df90fa2a308f2/tests/e2e-test.spec.js#L58) `waitForDbt(client)` it should succeed, but it [fails](https://github.com/medic/cht-sync/actions/runs/11835502600/job/32978409938) with:

```
   Main workflow Test Suite
Importing docs
Waiting for DBT
    1) "before all" hook in "Main workflow Test Suite"


  0 passing (35s)
  1 failing

  1) Main workflow Test Suite
       "before all" hook in "Main workflow Test Suite":
     Error: DBT models missing records after 30s
      at waitForDbt (file:///home/runner/work/cht-sync/cht-sync/tests/e2e-test.spec.js:33:11)
      at waitForDbt (file:///home/runner/work/cht-sync/cht-sync/tests/e2e-test.spec.js:47:10)
      at async Context.<anonymous> (file:///home/runner/work/cht-sync/cht-sync/tests/e2e-test.spec.js:58:5)
```

**Describe the improvement you'd like**
We should fail the CI test if it fails in CI.  We should also fix the test so it succeeds (and so does CI then)

**Describe alternatives you've considered**
NA

**Comment by mrjones-plip** [comment]
Digging into the docker logs, I see this error in postgres:

```
2024-11-15 20:26:46.197 UTC [42] STATEMENT:  SELECT * FROM dbt.reports                                 │
2024-11-15 20:26:47.199 UTC [42] ERROR:  relation "dbt.reports" does not exist at character 15 
```

That's coming from [this query](https://github.com/medic/cht-sync/blob/98771d2ea2c78ea27994d28d340df90fa2a308f2/tests/e2e-test.spec.js#L37):

```js
const dbtReports = await pgClient.query(`SELECT * FROM ${pgSchema}.reports`);
```

So `pgSchema` is set to `dbt`, but the actual schema is called `v1`.  If I change the schema name to `v1` in the environments file for both  [postgres](https://github.com/medic/cht-sync/blob/98771d2ea2c78ea27994d28d340df90fa2a308f2/tests/.e2e-env#L5) and for [dbt](https://github.com/medic/cht-sync/blob/98771d2ea2c78ea27994d28d340df90fa2a308f2/tests/.e2e-env#L8) all but 2 tests pass:

```
POSTGRES_SCHEMA="v1"
DBT_POSTGRES_SCHEMA="v1"
```

Here's the failing 2 tests:

```  
 Container cht-sync-postgres-1  Starting                                                                                                                                                                                                      
 Container cht-sync-postgres-1  Started                                                                                                                                                                                                       
      ✔ should handle PostgreSQL downtime gracefully (27103ms)                                                                                                                                                                                
    Incremental sync                                                                                                                                                                                                                          
      ✔ should process document edits (18283ms)                                                                                                                                                                                               
      1) should process contact deletes                                                                                                                                                                                                       
      ✔ should process person deletes (18050ms)                                                                                                                                                                                               
      2) should process report deletes                                                                                                                                                                                                        
      ✔ should process incremental inserts (18034ms)                                                                                                                                                                                          
    Conflict resolution                                                                                                                                                                                                                       
Failed to edit document with id 00172650-a2d1-540b-b308-d53ff75f102c: Document update conflict.                                                                                                                                               
      ✔ should handle update conflicts (19065ms)                                                                                                                                                                                              
Failed to delete document with id 00172650-a2d1-540b-b308-d53ff75f102c: Document update conflict.                                                                                                                                             
      ✔ should handle delete conflicts (19056ms)                                                                                                                                                                                              
                                                                                                                                                                                                                                              
  14 passing (3m)                                                                                                                                             
  2 failing                                                                                                                                                   
                                                                                                                                                              
  1) Main workflow Test Suite                                                                                                                                 
       Incremental sync                                                                                                                                       
         should process contact deletes:                                                                                                                      
                                                                                                                                                              
      AssertionError: expected 1 to equal +0                                                                                                                  
      + expected - actual                                                                                                                                     
                                                                                                                                                              
      -1                                                                                                                                                      
      +0                                                                                                                                                      
                                                                                                                                                              
      at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1038:12)                                                                           
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)                                                                           
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)                                                            
      at Proxy.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)                                                                    
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)                                                           
      at Proxy.<anonymous> (node_modules/chai-exclude/chai-exclude.js:122:21)                                                                                 
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)                                                           
      at Context.<anonymous> (file:///home/mrjones/Documents/MedicMobile/cht-sync/tests/e2e-test.spec.js:217:49)                                              
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                           
                                                                                                                                                              
  2) Main workflow Test Suite                                                                                                                                 
       Incremental sync                
         should process report deletes:                                        
                                       
      AssertionError: expected 1 to equal +0                                   
      + expected - actual
                                       
      -1                                                                       
      +0                                                                       
                                                                               
      at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1038:12)                                                                            
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)                                                                            
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)                                                             
      at Proxy.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)                                                                     
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)                                                           
      at Proxy.<anonymous> (node_modules/chai-exclude/chai-exclude.js:122:21)                                                                                 
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)                                                           
      at Context.<anonymous> (file:///home/mrjones/Documents/MedicMobile/cht-sync/tests/e2e-test.spec.js:245:48)                                              
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)   
```

**Comment by mrjones-plip** [comment]
I noticed that we both don't `return false` and `throw new Error()` in the `waitForDbt()` [call](https://github.com/medic/cht-sync/blob/98771d2ea2c78ea27994d28d340df90fa2a308f2/tests/e2e-test.spec.js#L33).  Elsewhere we use the a `return` and `console.error()`, for example in the ``postgres-utils.js` [file](https://github.com/medic/cht-sync/blob/98771d2ea2c78ea27994d28d340df90fa2a308f2/tests/utils/postgres-utils.js#L35). 

Maybe this is causing the test to not error out on GH CI?
